"""Shared fixtures. Integration fixtures generate real videos with ffmpeg lavfi."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest

from vidkit.config import Settings
from vidkit.core.ffmpeg import FFmpeg
from vidkit.core.probe import ProbeService
from vidkit.exceptions import FFmpegNotFoundError

if TYPE_CHECKING:
    from pathlib import Path

FIXTURE_DURATION = 30.0


def _make_ffmpeg() -> FFmpeg | None:
    try:
        return FFmpeg(Settings())
    except FFmpegNotFoundError:
        return None


@pytest.fixture(scope="session")
def ffmpeg_wrapper() -> FFmpeg:
    wrapper = _make_ffmpeg()
    if wrapper is None:
        pytest.skip("ffmpeg/ffprobe not available")
    wrapper.preflight()
    return wrapper


@pytest.fixture(scope="session")
def probe_service(ffmpeg_wrapper: FFmpeg) -> ProbeService:
    return ProbeService(ffmpeg_wrapper)


@pytest.fixture
def ffmpeg_env(ffmpeg_wrapper: FFmpeg, monkeypatch: pytest.MonkeyPatch) -> None:
    """Point VIDKIT_* env at the discovered binaries so CLI runs find them."""
    monkeypatch.setenv("VIDKIT_FFMPEG_PATH", str(ffmpeg_wrapper.ffmpeg_path))
    monkeypatch.setenv("VIDKIT_FFPROBE_PATH", str(ffmpeg_wrapper.ffprobe_path))


def generate_video(
    ffmpeg: FFmpeg,
    path: Path,
    *,
    duration: float = FIXTURE_DURATION,
    metadata: dict[str, str] | None = None,
) -> Path:
    """Create a small H.264/AAC mp4 with 1s keyframe spacing and injected tags."""
    args = [
        "-y",
        "-f",
        "lavfi",
        "-i",
        f"testsrc=duration={duration}:size=320x240:rate=24",
        "-f",
        "lavfi",
        "-i",
        f"sine=frequency=440:duration={duration}",
        "-map",
        "0:v",
        "-map",
        "1:a",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-pix_fmt",
        "yuv420p",
        "-g",
        "24",
        "-keyint_min",
        "24",
        "-sc_threshold",
        "0",
        "-c:a",
        "aac",
        "-b:a",
        "96k",
    ]
    tags = (
        metadata
        if metadata is not None
        else {
            "title": "VidKit Test Video",
            "comment": "generated by the vidkit test suite",
            "creation_time": "2020-01-02T03:04:05.000000Z",
            "location": "+37.7749-122.4194/",
        }
    )
    for key, value in tags.items():
        args += ["-metadata", f"{key}={value}"]
    args += ["-metadata:s:v:0", "handler_name=Suspicious Device Video"]
    args.append(str(path))
    ffmpeg.run_ffmpeg(args, timeout=300.0)
    return path


@pytest.fixture(scope="session")
def fixture_video(ffmpeg_wrapper: FFmpeg, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A 30s tagged video shared (read-only) across the whole session."""
    path = tmp_path_factory.mktemp("media") / "sample.mp4"
    return generate_video(ffmpeg_wrapper, path)


@pytest.fixture
def corrupt_video(tmp_path: Path) -> Path:
    path = tmp_path / "broken.mp4"
    path.write_bytes(b"this is definitely not an mp4 container" * 64)
    return path
